<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 dancing-michelle.gltf -T -t -s -u
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations, useSuspense } from '@threlte/extras';

	type ActionName = 'Flair' | 'HipHop2' | 'HipHop1' | 'SillyDancing' | 'HipHop3' | 'SambaDancing';

	type $$Props = Props<THREE.Group> & {
		currentAction?: ActionName;
		transitionDuration?: number;
	};
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	const suspend = useSuspense();

	type GLTFResult = {
		nodes: {
			Ch03: THREE.SkinnedMesh;
			mixamorigHips: THREE.Bone;
		};
		materials: {
			Ch03_Body: THREE.MeshStandardMaterial;
		};
	};

	let allActions: ActionName[] = ['HipHop2', 'HipHop1', 'SillyDancing', 'HipHop3'];

	let lastAction: ActionName | undefined = undefined;
	export let currentAction: ActionName | undefined = 'HipHop1';
	export let transitionDuration: number = 0.5;

	$: if (currentAction && $actions[currentAction] && lastAction !== currentAction) {
		if (!lastAction) {
			let action = $actions[currentAction];
			if (action) {
				action.play();
				mixer.addEventListener('loop', () => {
          if(!currentAction) return;
          let index = allActions.indexOf(currentAction);
          if (index === allActions.length - 1) {
            index = 0;
          } else {
            index++;
          }
          currentAction = allActions[index];
				});
			}
		} else {
			transitionTo(currentAction);
		}
		lastAction = currentAction;
	}

	const transitionTo = (nextActionKey: ActionName, duration = transitionDuration) => {
		if (!lastAction) return;
		const action = $actions[lastAction];
		const nextAction = $actions[nextActionKey];

		if (!nextAction || action === nextAction) return;

		nextAction.enabled = true;
		if (action) {
			action.crossFadeTo(nextAction, duration, true);
		}
		nextAction.play();
	};

	const gltf = suspend(
		useGltf<GLTFResult>('/fun-heros/models/dancing-michelle-transformed.glb', { useDraco: true })
	);
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="AuxScene" scale={0.13}>
			<T.Group name="AuxScene_1">
				<T.Group position={[0, -82.94, -1.3]}>
					<T is={gltf.nodes.mixamorigHips} />
					<T.SkinnedMesh
						name="Ch03"
						castShadow
						receiveShadow
						geometry={gltf.nodes.Ch03.geometry}
						material={gltf.materials.Ch03_Body}
						skeleton={gltf.nodes.Ch03.skeleton}
					/>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
